version: '3.8'

services:
  backend:
    build:
      context: ../landing-page_template_api
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '8000:8000'
    env_file:
      - ../landing-page_template_api/.env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

nextjs-app:
  build: .
  container_name: nextjs-app
  ports:
    - '3000:3000'
  depends_on:
    - backend
  env_file:
    - .env
  environment:
    - NODE_ENV=production
    - NEXT_PUBLIC_API_URL=http://backend:8000/api/v1
  restart: unless-stopped
  networks:
    - app-network

networks:
  app-network:
    driver: bridge
